spring.profiles.active: production
server.port: 8082

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/${databaseName}"
    username: "${username}"
    password: "${password}"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      format_sql: true
    properties.hibernate.default_schema: "${schemaName}"

liquibase:
  change-log: classpath:/liquibase/changelog.xml
  default-schema: "${schemaName}"
